SELECT 
  distinct FI.FOOD_ITEM_ID, FI.FOOD_ITEM_NAME, FI.FOOD_ITEM_IMAGE_URL, FI.FOOD_ITEM_DESCRIPTION, FI.FOOD_ITEM_DESCRIPTION_TAGS, FI.FOOD_ITEM_STATE 
FROM 
 FOOD_ITEM_OFFER FIP, PROVIDER P, FOOD_ITEM FI
WHERE  
  FIP.PROVIDER_ID = P.PROVIDER_ID
  AND FIP.FOOD_ITEM_ID = FI.FOOD_ITEM_ID
  AND FI.FOOD_ITEM_STATE = 'ACTIVE'
  AND P.PROVIDER_STATE = 'ACTIVE'
  AND P.PROVIDER_ADDRESS_ZIP_CODE in (${zip_codes})