SELECT NEIGHBOURING_ZD.ZIP_CODE
FROM ZIP_DATA ZD, ZIP_DATA NEIGHBOURING_ZD
WHERE ZD.ZIP_CODE = '${zip_code}'
AND sqrt( 
           POWER((69.1 * (NEIGHBOURING_ZD.LATTITUDE - ZD.LATTITUDE)), 2) + 
           POWER((69.1 * (NEIGHBOURING_ZD.LONGITUDE - ZD.LONGITUDE) * cos(ZD.LATTITUDE/57.3)), 2)
         ) < '${distance_in_miles}'