SELECT 
  distinct FI.* 
FROM 
 FOOD_ITEM_OFFER FIO, PROVIDER P, FOOD_ITEM FI
WHERE  
  FIO.PROVIDER_ID = P.PROVIDER_ID
  AND FIO.FOOD_ITEM_ID = FI.FOOD_ITEM_ID
  AND FI.FOOD_ITEM_STATE = 'ACTIVE'
  AND P.PROVIDER_STATE = 'ACTIVE'
  AND FIO.OFFER_STATE = 'ACTIVE'
  AND FIO.AVAILABLE_QUANTITY > 0
  AND date(FIO.OFFER_DAY) = STR_TO_DATE('${offer_day}','%Y-%m-%d')
  AND P.PROVIDER_ADDRESS_ZIP_CODE in (${zip_codes})